#!/usr/bin/env ansible-playbook

---
# File: ~/.ansible/liveuser.yml

- name: Setup & configuration script
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Print effective username
      debug: var=username

    - name: Print system information
      debug: var=systemos
