#!/usr/bin/env ansible-playbook

---
# File: ~/.ansible/liveuser.yml

- name: Setup & config localhost
  connection: local
  gather_facts: no
  hosts: localhost
  tasks:

    - name: Check for existing facts
      stat: path=~/.ansible/facts/localhost
      register: stat_result

    # - name: Print facts exist parameter
    #   debug: var=stat_result

    - name: Loading facts first time
      setup: gather_subset=!all,!any,facter
      when: stat_result.stat.exists == False

    - name: Print effective username
      debug: var=username

    - name: Print system information
      debug: var=systemos
